import { Avatar } from '@pulse-buddy/shared-types';

export const BUILTIN_AVATARS: Avatar[] = [
  {
    id: 'pip-penguin',
    name: 'Pip the Penguin',
    description: 'A cheerful Antarctic companion who loves water breaks, healthy snacks, and cheering your wins!',
    type: 'animated_svg',
    category: 'animals',
    supportedStates: ['idle', 'enter', 'walk', 'happy', 'concerned', 'acknowledge', 'celebrate', 'exit'],
    previewUrl: 'avatar-pip',
    isCustom: false,
    isFavorite: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'dr-robo',
    name: 'Dr. Robo Caretaker',
    description: 'A precision healthcare robot with floating thrusters, heart monitors, and friendly chime alerts.',
    type: 'animated_svg',
    category: 'robots',
    supportedStates: ['idle', 'enter', 'turn', 'happy', 'concerned', 'acknowledge', 'celebrate', 'thinking', 'exit'],
    previewUrl: 'avatar-robo',
    isCustom: false,
    isFavorite: false,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'maya-yogi',
    name: 'Maya the Mindful Guide',
    description: 'A serene human mindfulness companion who guides posture resets, deep breathing, and habit focus.',
    type: 'animated_svg',
    category: 'humans',
    supportedStates: ['idle', 'enter', 'walk', 'happy', 'concerned', 'acknowledge', 'celebrate', 'thinking', 'exit'],
    previewUrl: 'avatar-maya',
    isCustom: false,
    isFavorite: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'sparky-rover',
    name: 'Sparky Rocket Rover',
    description: 'An enthusiastic high-speed rover vehicle with bouncy suspension and celebratory rocket boosts!',
    type: 'animated_svg',
    category: 'vehicles',
    supportedStates: ['idle', 'enter', 'run', 'turn', 'happy', 'acknowledge', 'celebrate', 'exit'],
    previewUrl: 'avatar-sparky',
    isCustom: false,
    isFavorite: false,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ember-dragon',
    name: 'Ember the Cozy Dragon',
    description: 'A tiny mythological purple dragon who gently breathes warm sparkles and curls up for wind-down routines.',
    type: 'animated_svg',
    category: 'fantasy',
    supportedStates: ['idle', 'enter', 'happy', 'concerned', 'acknowledge', 'celebrate', 'exit'],
    previewUrl: 'avatar-ember',
    isCustom: false,
    isFavorite: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cosmo-astronaut',
    name: 'Cosmo the Spacewalker',
    description: 'A zero-G astronaut explorer with visor reflections, thumbs-up gestures, and cosmic enthusiasm.',
    type: 'animated_svg',
    category: 'custom',
    supportedStates: ['idle', 'enter', 'walk', 'happy', 'concerned', 'acknowledge', 'celebrate', 'thinking', 'exit'],
    previewUrl: 'avatar-cosmo',
    isCustom: false,
    isFavorite: false,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];
