const{contextBridge,ipcRenderer:i}=require('electron');
contextBridge.exposeInMainWorld('api',{
 get:()=>i.invoke('get'),
 save:d=>i.invoke('save',d),
 saveAsset:(id,b64)=>i.invoke('saveAsset',id,b64),
 getAsset:id=>i.invoke('getAsset',id),
 deleteAsset:id=>i.invoke('deleteAsset',id),
 createReminder:r=>i.invoke('createReminder',r),
 updateReminder:(id,u)=>i.invoke('updateReminder',id,u),
 deleteReminder:id=>i.invoke('deleteReminder',id),
 setSetting:(k,v)=>i.invoke('setSetting',k,v),
 test:r=>i.invoke('test',r),
 pause:m=>i.invoke('pause',m),
 answer:(id,a)=>i.invoke('answer',id,a),
 ignore:b=>i.send('ignore',b),
 closeOverlay:()=>i.send('close-overlay'),
 onFire:cb=>i.on('fire',(e,d)=>cb(d)),
 onRefresh:cb=>i.on('refresh',()=>cb())
});
